packages:
  - packages/**
  - blocklets/**
onlyBuiltDependencies:
  - core-js
  - core-js-pure
  - esbuild
  - fast-folder-size
  - protobufjs
  - sqlite3
overrides:
  '@abtnode/cron': ^1.16.54-beta-20251021-070951-25e3083c
  '@arcblock/did': ^1.26.2
  '@arcblock/did-ext': ^1.26.2
  '@arcblock/did-util': ^1.26.2
  '@arcblock/jwt': ^1.26.2
  '@arcblock/validator': ^1.26.2
  '@arcblock/vc': ^1.26.2
  '@arcblock/ws': ^1.26.2
  '@blocklet/constant': ^1.16.54-beta-20251021-070951-25e3083c
  '@blocklet/js-sdk': ^1.16.54-beta-20251021-070951-25e3083c
  '@blocklet/logger': ^1.16.54-beta-20251021-070951-25e3083c
  '@blocklet/sdk': ^1.16.54-beta-20251021-070951-25e3083c
  '@mui/icons-material': ^7.1.2
  '@mui/material': ^7.1.2
  '@mui/system': ^7.1.1
  '@ocap/asset': ^1.26.2
  '@ocap/client': link:../../../Library/pnpm/global/5/node_modules/@ocap/client
  '@ocap/contract': ^1.26.2
  '@ocap/mcrypto': ^1.26.2
  '@ocap/message': ^1.26.2
  '@ocap/proto': ^1.26.2
  '@ocap/types': ^1.26.2
  '@ocap/util': ^1.26.2
  '@ocap/wallet': ^1.26.2
  '@tus/file-store': 1.0.0
  '@tus/server': 1.0.0
  '@uppy/companion': 4.15.1
  '@uppy/core': 3.13.1
  '@uppy/dashboard': 3.9.1
  '@uppy/drag-drop': 3.1.1
  '@uppy/drop-target': 2.1.0
  '@uppy/file-input': 3.1.2
  '@uppy/golden-retriever': 3.2.0
  '@uppy/image-editor': 2.4.6
  '@uppy/locales': 3.5.4
  '@uppy/progress-bar': 3.1.1
  '@uppy/provider-views': 3.13.0
  '@uppy/react': 3.4.0
  '@uppy/status-bar': 3.3.3
  '@uppy/tus': 3.5.5
  '@uppy/unsplash': 3.3.1
  '@uppy/url': 3.6.1
  '@uppy/webcam': 3.4.2
  p-queue: 6.6.2
  p-retry: 4.6.1
  preact: 10.20.1
